name: Default


on: push


jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3.3.1
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure Cache Is Healthy
        if: runner.os != 'Windows' && steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version > /dev/null 2>&1 || rm -rf .venv
      - run: poetry install -vv --remove-untracked
      - uses: pre-commit/action@v3.0.0
  test-local-action-miss:
    name: Test Local Action With Cache Miss
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
    steps:
      - uses: actions/checkout@v3
      - id: local-action
        uses: ./
        with:
          cache-key-suffix: ${{ github.run_number }}
          python-version: ${{ matrix.python-version }}
      - name: check outputs.python-version
        env:
          MATRIX_PYTHON_VERSION: ${{ matrix.python-version }}
          OUTPUTS_PYTHON_VERSION: ${{ steps.local-action.outputs.python-version }}
        if: '!startsWith(steps.local-action.outputs.python-version, matrix.python-version)'
        run: |
          echo "outputs.python-version=${OUTPUTS_PYTHON_VERSION}"
          echo "matrix.python-version=${MATRIX_PYTHON_VERSION}"
          exit 1
      - name: check outputs.cache-hit (miss)
        env:
          CACHE_HIT_VALUE: ${{ steps.local-action.outputs.cache-hit }}
        if: steps.local-action.outputs.cache-hit == 'true'
        run: |
          echo "outputs.cache-hit=${CACHE_HIT_VALUE}"
          exit 1
      - name: check poetry
        run: poetry --version
      - name: ensure pre-commit is installed
        run: poetry run pre-commit sample-config
  test-local-action-hit:
    # This has to be run after the miss as the cache is not uploaded until the
    # the job is finished.
    name: Test Local Action With Cache Hit
    needs: test-local-action-miss
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
    steps:
      - uses: actions/checkout@v3
      - id: local-action
        uses: ./
        with:
          cache-key-suffix: ${{ github.run_number }}
          poetry-install: false
          python-version: ${{ matrix.python-version }}
      - name: check outputs.cache-hit (hit)
        env:
          CACHE_HIT_VALUE: ${{ steps.local-action.outputs.cache-hit }}
        if: steps.local-action.outputs.cache-hit != 'true'
        run: |
          echo "outputs.cache-hit=${CACHE_HIT_VALUE}"
          exit 1
      - name: ensure pre-commit is installed
        run: poetry run pre-commit sample-config
